### ISSUE TITLE
Maintenance of the package

### ISSUE THREAD

**Issue by garbinmarcelo** [laander/vue-modular#2]
Hello, how are you?

I work with Laravel and I'm joining a project where the client is VueJS, currently at Laravel I work with modules and I found the idea of working at Vuejs with this organization interesting too.

My question is about the use of this package in the current version of Vuejs, is it compatible yet? have you used in your projects?

I thank you for your attention and thank you for making this package available.

**Comment by laander** [comment]
Hi there, it works with Vue 2.x and I've used it for a few hobby projects. Just note that there's barely any code at all in this package - just a few codified conventions to help glue modules together - the rest is methodology.

**Comment by garbinmarcelo** [comment]
> Hi there, it works with Vue 2.x and I've used it for a few hobby projects. Just note that there's barely any code at all in this package - just a few codified conventions to help glue modules together - the rest is methodology.

Thanks for responding, I really like this idea of modules, especially for larger applications where I see better code organization and responsibilities.

I will use your package in a project that I am starting.

Thank you for sharing this package and your knowledge.
