### ISSUE TITLE
Demonstrative project

### ISSUE THREAD

**Issue by garbinmarcelo** [laander/vue-modular#3]
Hello,

Would you have any demonstration (repository) of how this package works? I'm trying to implement in a template that already existed some routes, but I'm having difficulty with that.

Thank you

**Comment by garbinmarcelo** [comment]
I have the following code in the main.js file:

```javascript
new Vue({
    router,
    store,
    render: h => h(App)
}).$mount('#app')
```

to use your package I use only the router and store within the code:
```javascript
Vue.use(VueModular, {
    modules: {
        authentication
    },
    router,
    store
})

```

can i define some pre-settings on the route that are valid for all others?

example:
```javascript
const router = new Router({
    mode: 'history',
    base: process.env.BASE_URL,
    scrollBehavior(){
        return {
            x: 0,
            y: 0
        }
    },
    routes: [
        // Redirect to 404 page, if no match found
        {
            path: '*',
            redirect: '/pages/error-404'
        }
    ]
})
```

@laander could you guide me? thank you

**Comment by garbinmarcelo** [comment]
well I made some changes and it looks like it worked, I just want to confirm this. One question I had is in which order are these modules loaded? can it affect the route issue or does it not affect the issue?

responding to myself, I believe it is in the import order =)

example:
```javascript
Vue.use(VueModular, {
    modules: {
        module1,
        module2,
        module3
    },
    router,
    store
})
```

**Comment by laander** [comment]
Check out the `expample` dir: https://github.com/laander/vue-modular/tree/master/example

Yes, the router you pass to `VueModular` is a fully-fledged vue router like you're used to. Your example should work.

Note that the load order of the modules cannot be guaranteed since `Object.keys` are used. It could have been an array instead of an object map, technically, but then naming the modules would have to be done by a property inside each module instead. Hmm

**Comment by garbinmarcelo** [comment]
> Check out the `expample` dir: https://github.com/laander/vue-modular/tree/master/example
> 
> Yes, the router you pass to `VueModular` is a fully-fledged vue router like you're used to. Your example should work.
> 
> Note that the load order of the modules cannot be guaranteed since `Object.keys` are used. It could have been an array instead of an object map, technically, but then naming the modules would have to be done by a property inside each module instead. Hmm

I hadn't really seen the example folder, my bad.

Okay, I'm certainly a little new with how Vuejs works and in a way javascript.

In this case, what you mean is that in the example I made earlier, module1 may not be loaded first? it is?

I ask this because I am apprehensive if in an application with multiple routes there may be some break in path redirects.
